services:
  - type: web
    name: content-backend
    env: node
    region: oregon
    buildCommand: cd backend && npm install --build-from-source
    startCommand: node server.js
    workingDirectory: ./backend
    envVars:
      - key: NODE_ENV
        value: production